version: "3.9"
services:
  web:
    image: my-app
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: "512M"
      restart_policy:
        condition: on-failure
  # node_exporter:
  #   container_name: node_exporter
  #   image: prom/node-exporter:latest
  #   command:
  #     - '--path.rootfs=/host'
  #   pid: host
  #   volumes:
  #     - '/:/host:ro'

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:latest
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./prometheus-data:/prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml

  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana-oss:latest
  #   ports:
  #     - "5000:3000"
  #   volumes:
  #     - ./grafana-data:/var/lib/grafana
