name: CI/CD Pipeline 

on: 
  push:
    branches: [ main ] 

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
      - uses: actions/checkout@v3 
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
      - run: npm install 
      - run: NODE_OPTIONS="--experimental-vm-modules" npm test 
      
      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run Docker container
        run: docker run my-app

      - name: Send metrics to Grafana Cloud
        run: node metrics.js
        env:
          GRAFANA_SA_TOKEN: ${{ secrets.GRAFANA_SA_TOKEN }}